In [1]:
import pandas as pd

# Use pd (da biblioteca pandas) e não df
df = pd.read_parquet('fipex-prices-latest-merged.parquet')

# Mostrar as primeiras 5 linhas
df.head()

,tipo_veiculo,codigo_fipe,nome_modelo,nome_marca,nome_combustivel,sigla_combustivel,ano_modelo,zero_km,valor_centavos,valor_formatado,mes_referencia,ano_referencia
0,moto,840015-6,ATV 100,ADLY,Gasolina,g,1990.0,False,0,"R$ 0,00",9,2012
1,moto,840015-6,ATV 100,ADLY,Gasolina,g,1991.0,False,0,"R$ 0,00",9,2012
2,moto,840015-6,ATV 100,ADLY,Gasolina,g,1992.0,False,0,"R$ 0,00",9,2012
3,moto,840015-6,ATV 100,ADLY,Gasolina,g,1993.0,False,0,"R$ 0,00",9,2012
4,moto,840015-6,ATV 100,ADLY,Gasolina,g,1994.0,False,0,"R$ 0,00",9,2012

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9276121 entries, 0 to 9276120
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   tipo_veiculo       object
 1   codigo_fipe        object
 2   nome_modelo        object
 3   nome_marca         object
 4   nome_combustivel   object
 5   sigla_combustivel  object
 6   ano_modelo         float64
 7   zero_km            bool
 8   valor_centavos     int64
 9   valor_formatado    object
 10  mes_referencia     int32
 11  ano_referencia     int32
dtypes: bool(1), float64(1), int32(2), int64(1), object(7)
memory usage: 716.6+ MB

In [5]:
df.describe()

         ano_modelo  valor_centavos  mes_referencia  ano_referencia
count  8.777727e+06    9.276121e+06    9.276121e+06    9.276121e+06
mean   2.003867e+03    9.030646e+06    6.463552e+00    2.015861e+03
std    9.399621e+00    2.128053e+07    3.470425e+00    6.828119e+00
min    1.981000e+03    0.000000e+00    1.000000e+00    2.001000e+03
25%    1.997000e+03    1.749200e+06    3.000000e+00    2.011000e+03
50%    2.003000e+03    3.811800e+06    6.000000e+00    2.017000e+03
75%    2.011000e+03    8.800500e+06    9.000000e+00    2.022000e+03
max    2.027000e+03    9.603000e+08    1.200000e+01    2.026000e+03

In [6]:
df.isna().sum()

tipo_veiculo              0
codigo_fipe               0
nome_modelo               0
nome_marca                0
nome_combustivel          0
sigla_combustivel         0
ano_modelo           498394
zero_km                   0
valor_centavos            0
valor_formatado           0
mes_referencia            0
ano_referencia            0
dtype: int64

In [10]:
pd.options.display.float_format = '{:.2f}'.format

df['valor_reais'] = df['valor_centavos']/100 

df_clean = df[df['valor_centavos'] > 0].copy()

df_clean['data_referencia'] = pd.to_datetime(
    df_clean['ano_referencia'].astype(str) + '-' + df_clean['mes_referencia'].astype(str) + '-01'
)

df_clean[['valor_reais','ano_modelo', 'ano_referencia']].describe()

       valor_reais  ano_modelo  ano_referencia
count   9276099.00  8777706.00      9276099.00
mean      90306.67     2003.87         2015.86
std      212805.48        9.40            6.83
min         338.00     1981.00         2001.00
25%       17492.00     1997.00         2011.00
50%       38118.00     2003.00         2017.00
75%       88005.00     2011.00         2022.00
max     9603000.00     2027.00         2026.00