In [1]:
import pandas as pd

In [2]:
PATH_SILVER = '../Data Layer/silver/fipe_silver.parquet'
DIR_GOLD = '../Data Layer/gold/'

# 1. Carregar a Silver
df = pd.read_parquet(PATH_SILVER)

# --- FATO 1: EVOLUÇÃO HISTÓRICA DE PREÇOS ---
# Agregamos por Ano de Referência e Marca para ver a tendência
fato_evolucao_precos = df.groupby(['ano_referencia', 'nome_marca'], observed=True).agg(
    preco_medio=('valor_reais', 'mean'),
    preco_mediano=('valor_reais', 'median'),
    volatilidade_preco=('valor_reais', 'std'),
    quantidade_registros=('valor_reais', 'count')
).reset_index()

fato_evolucao_precos.to_parquet('../Data Layer/gold/fato_evolucao_precos.parquet')

In [3]:
fato_evolucao_precos.head()

,ano_referencia,nome_marca,preco_medio,preco_mediano,volatilidade_preco,quantidade_registros
0,2016,ACURA,28020.727778,25008.0,12202.728163,180
1,2016,ADLY,2608.854167,2207.0,1054.719069,192
2,2016,AGRALE,49886.081623,43544.0,42269.366195,4141
3,2016,ALFA ROMEO,22776.683333,14981.5,15137.656392,660
4,2016,AM GEN,233044.194444,220521.0,34834.334635,108

In [4]:
fato_depreciacao = df.groupby(['nome_modelo', 'idade_veiculo'], observed=True).agg(
    valor_medio_por_idade=('valor_reais', 'mean')
).reset_index()

fato_depreciacao.to_parquet('../Data Layer/gold/fato_depreciacao.parquet')

In [5]:
fato_depreciacao.head()

                         nome_modelo  idade_veiculo  valor_medio_por_idade
0        001 Flagship Awd (Elétrico)            0.0          423713.571429
1        001 Flagship Awd (Elétrico)            1.0          450133.500000
2         001 Premium Awd (Elétrico)            0.0          385073.571429
3         001 Premium Awd (Elétrico)            1.0          396361.500000
4  10-160 E Delivery 2P (Diesel)(E5)           -1.0          131093.705882

In [6]:
dim_veiculos = df[['nome_marca','nome_modelo','tipo_veiculo']].drop_duplicates().reset_index(drop = True)
dim_veiculos.to_parquet('../Data Layer/gold/dim_veiculos.parquet')

In [7]:
datas = pd.date_range(start='2010-01-01', end='2026-12-31', freq='D')

dim_calendario = pd.DataFrame(datas, columns=['data'])

dim_calendario['ano'] = dim_calendario['data'].dt.year
dim_calendario['mes_num'] = dim_calendario['data'].dt.month
dim_calendario['mes_nome'] = dim_calendario['data'].dt.strftime('%B')
dim_calendario['trimestre'] = dim_calendario['data'].dt.quarter
dim_calendario['ano_mes'] = dim_calendario['data'].dt.strftime('%Y-%m')

dim_calendario.to_parquet('../Data Layer/gold/dim_calendario.parquet', index=False)

print("Dimensão Calendário criada com sucesso!")

Dimensão Calendário criada com sucesso!